Add AzureBlobOptions and manually validate
umbraco/Umbraco.Cloud.StorageProviders.AzureBlob pull request #1
Opened 2021-08-27 09:23 UTC by ronaldbarendse

This PR is the result of my initial review and contains the following changes/improvements:
- Updated NuGet dependencies and cleaner project file
- Add `AzureBlobOptions` class to bind and validate the required values, plus to generate the connection string based on the endpoint and shared access signature;

Other than this, we should ensure the version of `Umbraco.StorageProviders.AzureBlob` is updated when that's officially released!

2021-08-27 09:28 UTC, p-m-j approved these changes

2021-08-27 12:09 UTC, rasmusjp requested changes
Nice, it was on my todo to at least remove the `Configure` part and do the configuration in `AddAzureBlobMediaFileSystem`

I have added a single suggestion I think we should add as part of this PR

2021-08-27 12:09 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
The environment variable we need to check has changed, it's now `UMBRACO__CLOUD__ISRUNNINGONCLOUD` wich should have the value `true`

```suggestion
            var isRunningOnCloud = Environment.GetEnvironmentVariable("UMBRACO__CLOUD__ISRUNNINGONCLOUD");
            if (isRunningOnCloud != "true") return;
```

2021-08-27 13:06 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
That's an easy fix, although I would argue we should ensure it's compared using `string.Equals(isRunningOnCloud, "true", StringComparison.InvariantCultureIgnoreCase)` or parsed as a boolean using `bool.TryParse()`. Would be very confusing if it stops working when the value is set to `True` 😉 

It this checked before creating the `ConfigurationBuilder` to prevent a possible expensive operation? Otherwise we might as well use `configuration.GetValue<bool>("IsRunningOnCloud")`, as the configuration only looks at environment variables anyway...

2021-08-27 14:01 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
Either way is fine, but I don't expect it to change as it's part of our provisioning.

The reason for checking the environment instead of using the configuration object is because we don't wan't to make it to easy to enable it locally by overriding the setting, and we'll ever only set the environment variable on Cloud

2021-08-27 14:52 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
Directly using `Environment` or the manually created configuration shouldn't matter in that case, right? In any case it's possible to add the environment variables in your `launchSettings.json`, so it's just an additional sanity check/enable flag, right?

2021-08-28 10:56 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
Updated to get the setting using `configuration.GetValue<bool>("IsRunningOnCloud")`, as that makes it cleaner and we always need it when running on Umbraco Cloud anyway.

2021-08-28 11:00 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            var azureBlobOptions = configuration.GetSection("Storage:AzureBlob").Get<AzureBlobOptions>();
Should we update this to `Storage:AzureBlob:Media`, so it's the same as the base package configuration and we have the possibility to setup other file systems (e.g. for Forms) in the future?
```suggestion
            var azureBlobOptions = configuration.GetSection("Storage:AzureBlob:Media").Get<AzureBlobOptions>();
```

2021-08-28 11:00 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobOptions.cs
> +        public string Endpoint { get; set; } = null!;
It would make more sense to change this property (and related environment variable) name to:
```suggestion
        public string BlobEndpoint { get; set; } = null!;
```

2021-08-28 11:00 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobOptions.cs
> +        public string ConnectionString => $"BlobEndpoint={Endpoint};SharedAccessSignature={SharedAccessSignature}";
If the property is renamed, this should also be updated:
```suggestion
        public string ConnectionString => $"BlobEndpoint={BlobEndpoint};SharedAccessSignature={SharedAccessSignature}";
```

2021-08-30 10:26 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            var azureBlobOptions = configuration.GetSection("Storage:AzureBlob").Get<AzureBlobOptions>();
I we need to have a forms filesystem it'll use the same credentials (we already do this for Heartcore on v8), so there's no need to change this

2021-08-30 10:29 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobOptions.cs
> +        public string Endpoint { get; set; } = null!;
The property is already nested in `AzureBlob` options, and the env. variable is also named `Umbraco:Cloud:Storage:AzureBlob:Endpoint` so it's already given it's the blob endpoint and I don't see any reason to change it

2021-08-30 10:33 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
I still think we should keep the env. variable check to make it explicit that it's the variable is required for it to run, it also makes it safer so we don't accidentally allow anyone to overwrite it on Cloud if we add another config source at one point

2021-08-30 12:58 UTC, sitereactor commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
I still don't understand why we want this. If the ~3 appsettings (required by the Umbraco Cloud specific configuration) is there then we enable it, if one or all of the required settings or not there than we don't enable it. I don't see a good reason for having yet another check of an arbitrary appsetting is needed, as if we want to hide or make it more difficult to use the configuration outside of Cloud.

2021-08-30 13:03 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
Sure we can remove it, it was only added because it was agreed at one point we should have this check in our Cloud assemblies to ensure we only loaded parts that were needed on Cloud when running on Cloud

2021-08-30 13:05 UTC, sitereactor commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
I think that was specific to licensed products/plugins

2021-08-30 13:10 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            if (string.IsNullOrEmpty(environment)) return;
@ronaldbarendse you can just remove the check then 👍

2021-08-31 06:58 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobOptions.cs
> +        public string Endpoint { get; set; } = null!;
It might indeed seem a bit repetitive, but my reasoning was to align it with the connection string key `BlobEndpoint=`.

2021-08-31 07:02 UTC, ronaldbarendse commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobComposer.cs
> +            var azureBlobOptions = configuration.GetSection("Storage:AzureBlob").Get<AzureBlobOptions>();
That makes sense, as both media and cache files are already stored in separate directories within the blob container 👍🏻

2021-08-31 08:58 UTC, rasmusjp commented on src/Umbraco.Cloud.StorageProviders.AzureBlob/AzureBlobOptions.cs
> +        public string Endpoint { get; set; } = null!;
I see your point, but we are already provisioning with the endpoint variable and don' want to change that now, so we'll keep it as it is

2021-08-31 08:58 UTC, merged